BgAuto/BgAuto/Controllers/CarController.cs
using BgAuto.Abstraction;
using BgAuto.Domain;
using BgAuto.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BgAuto.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarService service;

        public CarController(ICarService _service)
        {
            this.service = _service;
        }

        public IActionResult All(string searchBrand, string searchModel, decimal searchPrice)
        {
            List<CarAllViewModel> car = service.GetCars()
                .Select(x => new CarAllViewModel
                {
                    Id = x.Id,
                    Image = x.Image,
                    CarNumber = x.CarNumber,
                    Color = x.Color,
                    Country = x.Country,
                    Brand = x.Brand,
                    Engine = x.Engine,
                    Extras = x.Extras,
                    Model = x.Model,
                    Year = x.Year,
                    Price = x.Price,
                    Discount = x.Discount,
                    Quantity = x.Quantity
                }).ToList();

            if (!String.IsNullOrEmpty(searchBrand))
            {
                car = car.Where(x => x.Brand.ToLower() == searchBrand.ToLower())
                .ToList();
            }
            else if (!String.IsNullOrEmpty(searchModel))
            {
                car = car.Where(x => x.Model.ToLower() == searchModel.ToLower())
            .ToList();
            }
            else if (!Decimal.Zero.Equals(searchPrice))
            {
                car = car.Where(x => x.Price == searchPrice)
                .ToList();
            }
            return View("All", car);
        }

        public IActionResult Details(string id)
        {
            var x = service.GetCar(id);

            CarDetailsViewModel detailsViewModel = new CarDetailsViewModel
            {
                Id = x.Id,
                Image = x.Image,
                CarNumber = x.CarNumber,
                Color = x.Color,
                Country = x.Country,
                Brand = x.Brand,
                Engine = x.Engine,
                Extras = x.Extras,
                Model = x.Model,
                Year = x.Year,
                Price = x.Price,
                Discount = x.Discount,
                Quantity = x.Quantity
            };

            return View("Details", detailsViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CarCreateViewModel car)
        {
            if (ModelState.IsValid)
            {
                var isCreated = service.Create(car.Image, car.CarNumber, car.Brand, car.Model, car.Year,
                    car.Engine, car.Color, car.Country, car.Extras, car.Price, car.Discount, car.Quantity);

                if (isCreated)
                {
                    return RedirectToAction("All");
                }
            }
            return View();
        }

        public IActionResult Edit(string id)
        {
            {
                Car item = service.GetCar(id);
                if (item == null)
                {
                    return NotFound();
                }
                CarCreateViewModel car = new CarCreateViewModel()
                {
                    Id = item.Id,
                    Image = item.Image,
                    CarNumber = item.CarNumber,
                    Color = item.Color,
                    Country = item.Country,
                    Brand = item.Brand,
                    Engine = item.Engine,
                    Extras = item.Extras,
                    Model = item.Model,
                    Year = item.Year,
                    Price = item.Price,
                    Discount = item.Discount,
                    Quantity = item.Quantity

                };
                return View(car);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, CarCreateViewModel createCar)
        {
            if (ModelState.IsValid)
            {
                var updated = service.UpdateCar(createCar.Id, createCar.Image, createCar.CarNumber, createCar.Brand, createCar.Model, 
                    createCar.Year, createCar.Engine, createCar.Color, createCar.Country, createCar.Extras, 
                    createCar.Price, createCar.Discount, createCar.Quantity);
                if (updated)
                {
                    return this.RedirectToAction("All");
                }
            }
            return View();
        }

        public IActionResult Delete(string id)
        {
            var item = service.GetCar(id);

            if (item == null)
            {
                return NotFound();
            }
            var deleteModel = new CarCreateViewModel

            {
                Id = item.Id,
                Image = item.Image,
                CarNumber = item.CarNumber,
                Color = item.Color,
                Country = item.Country,
                Brand = item.Brand,
                Engine = item.Engine,
                Extras = item.Extras,
                Model = item.Model,
                Year = item.Year,
                Quantity = item.Quantity
            };
            return View(deleteModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(string id, IFormCollection collection)
        {
            var deleted = service.RemoveCar(id);
            if (deleted)
            {
                return this.RedirectToAction("All");
            }
            else
            {
                return View();
            }
        }
        public IActionResult MakeDiscount(string id)
        {
            var x = service.GetCar(id);

            CarPromotionViewModel product = new CarPromotionViewModel
            {
                Id = x.Id,
                Model = x.Model,
                Brand = x.Brand,
                OldPrice = x.Price,
                NewPrice = x.Price,
                Image = x.Image
            };
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MakeDiscount(string id, int discount)
        {
            service.MakeDiscount(id, discount);

            return this.RedirectToAction("All");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveDiscount(string id, int discount)
        {
            service.RemoveDiscount(id);

            return this.RedirectToAction("All");
        }
        public IActionResult AllDiscounts()
        {
            var products = new List<CarAllViewModel>();

            foreach (var product in service.GetCars().Where(x => x.Discount != 0))
            {
                var viewModel = new CarAllViewModel
                {
                    Id = product.Id,
                    Image = product.Image,
                    CarNumber = product.CarNumber,
                    Color = product.Color,
                    Country = product.Country,
                    Brand = product.Brand,
                    Engine = product.Engine,
                    Extras = product.Extras,
                    Model = product.Model,
                    Year = product.Year,
                    Price = product.Price,
                    Discount = product.Discount
                };
                products.Add(viewModel);
            }
            return View("All", products);
        }
        public IActionResult Promotion()
        {
            List<CarAllViewModel> car = service.GetCars().Where(x => x.Discount != 0)
                .Select(x => new CarAllViewModel
                {
                    Id = x.Id,
                    Image = x.Image,
                    CarNumber = x.CarNumber,
                    Color = x.Color,
                    Country = x.Country,
                    Brand = x.Brand,
                    Engine = x.Engine,
                    Extras = x.Extras,
                    Model = x.Model,
                    Year = x.Year,
                    Price = x.Price,
                    Discount = x.Discount,
                    Quantity = x.Quantity
              
                }).ToList();


            return View("Promotion", car);
        }
    }
}

BgAuto/BgAuto/Controllers/ClientsController.cs
using BgAuto.Abstraction;
using BgAuto.Domain;
using BgAuto.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Manage.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BgAuto.Controllers
{
    public class ClientsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IClientService service;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ILogger<ChangePasswordModel> logger;

        public ClientsController(UserManager<ApplicationUser> userManager,
            IClientService service,
            SignInManager<ApplicationUser> signInManager,
             ILogger<ChangePasswordModel> logger)
        {
            this.userManager = userManager;
            this.service = service;
            this.signInManager = signInManager;
            this.logger = logger;
        }
        // GET: ClientsController
        public IActionResult All()
        {
            var employees = service.GetClients()
                .Select(x => new ClientListingModel
                {
                    Id = x.Id,
                    Phone = x.Phone,
                    FirstName = x.User.FirstName,
                    LastName = x.User.LastName,
                    Address = x.Address,
                    UserId = x.UserId,
                    UserName = x.User.UserName,
                    Email = x.User.Email
                }).ToList();


            employees = employees.OrderBy(x => x.UserName).ToList();
            return View(employees);
        }

        // GET: ClientsController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ClientCreateViewModel clientCreateViewModel)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var userIdAlreadyClient = this.service
                .GetClients()
                .Any(d => d.UserId == userId);
                var iscreated = service.CreateClient(clientCreateViewModel.PhoneNumber, clientCreateViewModel.Address, userId);
                if(iscreated)
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(clientCreateViewModel);
        }
    }
}

BgAuto/BgAuto/Controllers/OrderController.cs
using BgAuto.Abstraction;
using BgAuto.Data;
using BgAuto.Domain;
using BgAuto.Models;
using BgAuto.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BgAuto.Controllers
{
    public class OrderController : Controller
    {

        private readonly IOrderService service;

        public OrderController(IOrderService _service)
        {
            this.service = _service;
        }
        public IActionResult All()
        {
            List<OrderListingViewModel> order = service.All()
                .Select(x => new OrderListingViewModel
                {
                    Id = x.Id,
                    Image = x.Car.Image,
                    CustomerId = x.CustomerId,
                    Customer = x.Customer.UserName,
                    Price = x.Car.Price * x.Quantity,
                    Model = x.Car.Model,
                    Brand = x.Car.Brand,
                    OrderedOn = x.OrderedOn.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    Quantity = x.Quantity

                }).ToList();
            return View(order);
        }
        public IActionResult My()
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            List<OrderListingViewModel> order = service.My(userId)
                .Select(x => new OrderListingViewModel
                {
                    Id = x.Id,
                    Image = x.Car.Image,
                    CustomerId = x.CustomerId,
                    Customer = x.Customer.UserName,
                    Price = x.Car.Price * x.Quantity,
                    Model = x.Car.Model,
                    Brand = x.Car.Brand,
                    OrderedOn = x.OrderedOn.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    Quantity = x.Quantity

                }).ToList();
            return View(order);
        }
        public IActionResult Create(string carId)
        {
            OrderCreateViewModel order = new OrderCreateViewModel()
            {
                CarId = carId,
                OrderedOn = DateTime.Now
            };
            return View(order);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OrderCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                var created = service.Create(viewModel.Id, viewModel.CustomerId, userId, viewModel.Customer, viewModel.CarId, viewModel.Car, viewModel.OrderedOn, viewModel.Quantity);

                if (created)
                {
                    return RedirectToAction("My");
                }
            }
            return RedirectToAction();
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

BgAuto/BgAuto/Controllers/TestDriveController.cs
using BgAuto.Abstraction;
using BgAuto.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BgAuto.Controllers
{
    public class TestDriveController : Controller
    {
        private readonly ITestDriveService service;

        public TestDriveController(ITestDriveService _service)
        {
            this.service = _service;
        }
        public IActionResult All()
        {
            List<TestDriveListingViewModel> testdrive = service.All()
                .Select(x => new TestDriveListingViewModel
                {
                    Id = x.Id,
                    Image = x.Car.Image,
                    Price = x.Car.Price,
                    CustomerId = x.CustomerId,
                    Customer = x.Customer.UserName,
                    Model = x.Car.Model,
                    Brand = x.Car.Brand,
                    OrderedOn = x.OrderedOn.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    TestOn = x.TestOn.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture)

                }).ToList();
            return View(testdrive);
        }
        public IActionResult My()
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            List<TestDriveListingViewModel> testdrive = service.My(userId)
                .Select(x => new TestDriveListingViewModel
                {
                    Id = x.Id,
                    Image = x.Car.Image,
                    Price = x.Car.Price,
                    CustomerId = x.CustomerId,
                    Customer = x.Customer.UserName,
                    Model = x.Car.Model,
                    Brand = x.Car.Brand,
                    OrderedOn = x.OrderedOn.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    TestOn = x.TestOn.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture)

                }).ToList();
            return View(testdrive);
        }
        public IActionResult Create(string carId)
        {
            TestDriveCreateBindingModel testDrive = new TestDriveCreateBindingModel()
            {
                CarId = carId,
                CustomerId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                OrderedOn = DateTime.Now
            };
            return View(testDrive);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TestDriveCreateBindingModel viewModel)
        {
            if (ModelState.IsValid)
            {
                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                var created = service.Create(viewModel.Id, viewModel.CustomerId, userId, viewModel.Customer, 
                    viewModel.CarId, viewModel.Car, viewModel.OrderedOn, viewModel.TestOn);

                if (created)
                {
                    return RedirectToAction("My");
                }
            }
            return RedirectToAction();
        }
    }
}

BgAuto/BgAuto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BgAuto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src ="https://kit.fontawesome.com/2ca93d86e5.js" crossorigin="anonymous"></script>
</head>
<body>
    <div>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BgAuto <i class="fas fa-car"></i></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="All">Car</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Promotion">Promo Offers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TestDrive" asp-action="My">My Test Drive</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="My">My Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Contacts">Contact Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ForUs" asp-action="ForUsPage">For Us</a>
                            </li>
                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item active">
                                    <div class="dropdown show">
                                        <a class="nav-link active dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin Action</a>

                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Create">Create New Car</a>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="All">Clients</a>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="All">Employees</a>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="TestDrive" asp-action="All">All Test Drive</a>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="All">All Orders</a>
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BgAuto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>